### ISSUE TITLE
你好，请问demo中你直接从timm中引入了vit，并没有像使用说明中去对attention部分使用装饰器装饰

### ISSUE THREAD

**Issue by 1104662797** [luo3300612/Visualizer#2]
你好，请问demo中你直接从timm中引入了vit，并没有像使用说明中去对attention部分使用装饰器装饰，还有就是如果对训练好的模型的代码加入visualzer装饰器仍然可以load model么？感谢了

**Comment by luo3300612** [comment]
demo里面的timm是我代码一起附带的timm，在这里面我用装饰器改了的

**Comment by jiangke-sr** [comment]
@1104662797 作者在 Attention#forward 加了呀
