### ISSUE TITLE
请问 demo 中 `cls_padding` 函数的作用为何？

### ISSUE THREAD

**Issue by Wuziyi616** [luo3300612/Visualizer#5]
您好，我看到您在 demo 中得到 attention map 后，还使用 `cls_padding` 函数进行了 padding，请问为何要这么做？谢谢

**Comment by luo3300612** [comment]
您好，因为vit里面的cls token也会有attention map，所以这里同时也可视化了cls token的attention map

**Comment by Wuziyi616** [comment]
理解了，感谢！
